In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.fillna(999)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,999.0,21.0,13495.0
1,alfa-romero,convertible,999.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,999.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,999.0,999.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,999.0,171.7,999,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,999.0,ohc,four,100.0,999.0,9995.0
87,volvo,sedan,104.3,188.8,999,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,999.0,23.0,13415.0

In [ ]:
df.fillna({"horsepower":np.mean(df['horsepower']), "wheel-base":np.mean(df['wheel-base'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.8,dohc,four,108.266667,21.0,13495.0
1,alfa-romero,convertible,99.219565,168.8,dohc,four,111.000000,21.0,16500.0
2,alfa-romero,hatchback,94.500000,171.2,ohcv,six,154.000000,NaN,16500.0
3,audi,sedan,99.800000,176.6,ohc,four,102.000000,24.0,13950.0
4,audi,sedan,99.400000,176.6,ohc,five,108.266667,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.7,ohc,four,85.000000,27.0,7975.0
82,volkswagen,sedan,99.219565,171.7,NaN,four,52.000000,37.0,7995.0
86,volkswagen,sedan,97.300000,NaN,ohc,four,100.000000,NaN,9995.0
87,volvo,sedan,104.300000,188.8,NaN,four,114.000000,23.0,12940.0
88,volvo,wagon,104.300000,188.8,ohc,four,108.266667,23.0,13415.0

In [ ]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [ ]:
df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df[df.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

In [ ]:
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df.fillna(df.mean())

<ipython-input-22-a2478f315f9e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.800000,dohc,four,108.297872,21.000000,13495.0
1,alfa-romero,convertible,99.072917,168.800000,dohc,four,111.000000,21.000000,16500.0
2,alfa-romero,hatchback,94.500000,171.200000,ohcv,six,154.000000,25.695652,16500.0
3,audi,sedan,99.800000,176.600000,ohc,four,102.000000,24.000000,13950.0
4,audi,sedan,99.400000,176.600000,ohc,five,108.297872,25.695652,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.700000,ohc,four,85.000000,27.000000,7975.0
82,volkswagen,sedan,99.072917,171.700000,NaN,four,52.000000,37.000000,7995.0
86,volkswagen,sedan,97.300000,173.767347,ohc,four,100.000000,25.695652,9995.0
87,volvo,sedan,104.300000,188.800000,NaN,four,114.000000,23.000000,12940.0
88,volvo,wagon,104.300000,188.800000,ohc,four,108.297872,23.000000,13415.0

In [ ]:
dfh=df[df['body-style']=="hatchback"]

In [ ]:
dfh.fillna(dfh.mean())

<ipython-input-25-ecf55eda71e8>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dfh.fillna(dfh.mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.5,171.200,ohcv,six,154.000000,32.727273,16500.000000
16,chevrolet,hatchback,88.4,141.100,l,three,77.363636,47.000000,5151.000000
17,chevrolet,hatchback,94.5,155.900,ohc,four,70.000000,38.000000,6295.000000
19,dodge,hatchback,93.7,157.300,ohc,four,68.000000,31.000000,6377.000000
20,dodge,hatchback,93.7,159.325,ohc,four,68.000000,32.727273,6229.000000
36,mazda,hatchback,93.1,159.100,NaN,four,77.363636,32.727273,5195.000000
37,mazda,hatchback,93.1,159.100,ohc,four,68.000000,31.000000,6095.000000
38,mazda,hatchback,93.1,159.100,ohc,four,68.000000,31.000000,6795.000000
39,mazda,hatchback,94.1,159.325,NaN,two,101.000000,17.000000,11845.000000
49,mitsubishi,hatchback,94.1,157.300,ohc,four,77.363636,37.000000,5389.000000
50,mitsubishi,hatchback,93.7,159.325,NaN,four,68.000000,31.000000,6189.000000
63,porsche,hatchback,98.4,175.700,dohcv,eight,77.363636,32.727273,7159.571429
66,toyota,hatchback,95.7,158.700,ohc,four,62.000000,35.000000,5348.000000
67,toyota,hatchback,95.7,158.700,ohc,four,62.000000,31.000000,6338.000000
68,toyota,hatchback,95.7,158.700,ohc,four,62.000000,31.000000,6488.000000